all:
	g++ -c -Iinc/ src/BigInt_Utils.cpp -o obj/BigInt_Utils.o
	g++ -c -Iinc/ src/BigUInt_Serial_Impl.cpp -o obj/BigUInt_Serial.o
	g++ -c -Iinc/ src/BigUInt.cpp -o obj/BigInt.o

clean:
	rm -r obj/*.o

