#!/bin/bash

echo "ADD =>"
echo "Serial:"
./add_s in_add
echo ""
echo "Parallel:"
./add_p in_add

echo ""
echo ""

echo "SUB => "
echo "Serial:"
./sub_s in_sub
echo ""
echo "Parallel:"
./sub_p in_sub

echo ""
echo ""

echo "MULT =>"
echo "Serial:"
./mult_s in_mul
echo ""
echo "Parallel:"
./mult_p in_mul

echo ""
echo ""

echo "AND =>"
echo "Serial:"
./and_s in_and
echo ""
echo "Parallel:"
./and_p in_and

echo ""
echo ""

echo "OR =>"
echo "Serial:"
./or_s in_or
echo ""
echo "Parallel:"
./or_p in_or

echo ""
echo ""

echo "XOR =>"
echo "Serial:"
./xor_s in_xor
echo ""
echo "Parallel:"
./xor_p in_xor

echo ""
echo ""

echo "NOT =>"
echo "Serial:"
./not_s in_not
echo ""
echo "Parallel:"
./not_p in_not

echo ""
echo ""

